// <auto-generated />
using System;
using Kancelaria.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kancelaria.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190723162203_CaseUpdate1")]
    partial class CaseUpdate1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Kancelaria.API.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CaseDetailID");

                    b.Property<string>("CaseName");

                    b.Property<bool>("Closed");

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Leader");

                    b.Property<string>("Signature");

                    b.Property<int?>("UserID");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("Kancelaria.API.Models.CaseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CaseID");

                    b.HasKey("Id");

                    b.ToTable("CasesDetails");
                });

            modelBuilder.Entity("Kancelaria.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Kancelaria.API.Models.Value", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("Kancelaria.API.Models.Case", b =>
                {
                    b.HasOne("Kancelaria.API.Models.User")
                        .WithMany("Cases")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
